language: r
sudo: required
dist: trusty
addons:
   apt:
     packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
r_packages:
  - sf
  - testthat
r_github_packages: 
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
